/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsReaderRouteImport } from './routes/settings.reader'
import { Route as SettingsAppRouteImport } from './routes/settings.app'
import { Route as ReaderChapterIdRouteImport } from './routes/reader.$chapterId'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ExtensionsProviderIdRouteImport } from './routes/extensions.$providerId'

const ThemeLazyRouteImport = createFileRoute('/theme')()
const OnboardingLazyRouteImport = createFileRoute('/onboarding')()
const MigrationLazyRouteImport = createFileRoute('/migration')()
const DiagnosticsLazyRouteImport = createFileRoute('/diagnostics')()
const BackupLazyRouteImport = createFileRoute('/backup')()

const ThemeLazyRoute = ThemeLazyRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/theme.lazy').then((d) => d.Route))
const OnboardingLazyRoute = OnboardingLazyRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))
const MigrationLazyRoute = MigrationLazyRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/migration.lazy').then((d) => d.Route))
const DiagnosticsLazyRoute = DiagnosticsLazyRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/diagnostics.lazy').then((d) => d.Route))
const BackupLazyRoute = BackupLazyRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backup.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsReaderRoute = SettingsReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppRoute = SettingsAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => SettingsRoute,
} as any)
const ReaderChapterIdRoute = ReaderChapterIdRouteImport.update({
  id: '/reader/$chapterId',
  path: '/reader/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsProviderIdRoute = ExtensionsProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => ExtensionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/backup': typeof BackupLazyRoute
  '/diagnostics': typeof DiagnosticsLazyRoute
  '/migration': typeof MigrationLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/theme': typeof ThemeLazyRoute
  '/extensions/$providerId': typeof ExtensionsProviderIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/reader': typeof SettingsReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/backup': typeof BackupLazyRoute
  '/diagnostics': typeof DiagnosticsLazyRoute
  '/migration': typeof MigrationLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/theme': typeof ThemeLazyRoute
  '/extensions/$providerId': typeof ExtensionsProviderIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/reader': typeof SettingsReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/backup': typeof BackupLazyRoute
  '/diagnostics': typeof DiagnosticsLazyRoute
  '/migration': typeof MigrationLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/theme': typeof ThemeLazyRoute
  '/extensions/$providerId': typeof ExtensionsProviderIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/reader': typeof SettingsReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extensions'
    | '/library'
    | '/search'
    | '/settings'
    | '/backup'
    | '/diagnostics'
    | '/migration'
    | '/onboarding'
    | '/theme'
    | '/extensions/$providerId'
    | '/manga/$id'
    | '/reader/$chapterId'
    | '/settings/app'
    | '/settings/reader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extensions'
    | '/library'
    | '/search'
    | '/settings'
    | '/backup'
    | '/diagnostics'
    | '/migration'
    | '/onboarding'
    | '/theme'
    | '/extensions/$providerId'
    | '/manga/$id'
    | '/reader/$chapterId'
    | '/settings/app'
    | '/settings/reader'
  id:
    | '__root__'
    | '/'
    | '/extensions'
    | '/library'
    | '/search'
    | '/settings'
    | '/backup'
    | '/diagnostics'
    | '/migration'
    | '/onboarding'
    | '/theme'
    | '/extensions/$providerId'
    | '/manga/$id'
    | '/reader/$chapterId'
    | '/settings/app'
    | '/settings/reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsRoute: typeof ExtensionsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  BackupLazyRoute: typeof BackupLazyRoute
  DiagnosticsLazyRoute: typeof DiagnosticsLazyRoute
  MigrationLazyRoute: typeof MigrationLazyRoute
  OnboardingLazyRoute: typeof OnboardingLazyRoute
  ThemeLazyRoute: typeof ThemeLazyRoute
  MangaIdRoute: typeof MangaIdRoute
  ReaderChapterIdRoute: typeof ReaderChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/reader': {
      id: '/settings/reader'
      path: '/reader'
      fullPath: '/settings/reader'
      preLoaderRoute: typeof SettingsReaderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app': {
      id: '/settings/app'
      path: '/app'
      fullPath: '/settings/app'
      preLoaderRoute: typeof SettingsAppRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reader/$chapterId': {
      id: '/reader/$chapterId'
      path: '/reader/$chapterId'
      fullPath: '/reader/$chapterId'
      preLoaderRoute: typeof ReaderChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$providerId': {
      id: '/extensions/$providerId'
      path: '/$providerId'
      fullPath: '/extensions/$providerId'
      preLoaderRoute: typeof ExtensionsProviderIdRouteImport
      parentRoute: typeof ExtensionsRoute
    }
  }
}

interface ExtensionsRouteChildren {
  ExtensionsProviderIdRoute: typeof ExtensionsProviderIdRoute
}

const ExtensionsRouteChildren: ExtensionsRouteChildren = {
  ExtensionsProviderIdRoute: ExtensionsProviderIdRoute,
}

const ExtensionsRouteWithChildren = ExtensionsRoute._addFileChildren(
  ExtensionsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppRoute: typeof SettingsAppRoute
  SettingsReaderRoute: typeof SettingsReaderRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppRoute: SettingsAppRoute,
  SettingsReaderRoute: SettingsReaderRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsRoute: ExtensionsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  BackupLazyRoute: BackupLazyRoute,
  DiagnosticsLazyRoute: DiagnosticsLazyRoute,
  MigrationLazyRoute: MigrationLazyRoute,
  OnboardingLazyRoute: OnboardingLazyRoute,
  ThemeLazyRoute: ThemeLazyRoute,
  MangaIdRoute: MangaIdRoute,
  ReaderChapterIdRoute: ReaderChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
