#!/bin/bash

# Verificar el sistema operativo
if [ "$OSTYPE" = "msys" ] || [ "$OSTYPE" = "win32" ]; then
  # Si es Windows, ejecutar npx desde cmd si es necesario
  if command -v npx.cmd 2> /dev/null; then
    npx.cmd lint-staged
  else
    cmd.exe /c npx lint-staged
  fi
else
  # Si no es Windows, intentar ejecutar npx lint-staged
	if command -v npx 2> /dev/null; then
    npx lint-staged
  else
    echo "El comando 'npx' no está disponible. Por favor, instale 'npx' para continuar."
    exit 1
  fi
fi
